/**
 * Class 10 Science · Chapter 5 "Life Processes": a realistic, CBSE-style
 * question set for testing paper generation on one chapter.
 *
 * Every item here is ORIGINAL wording written for PaperFlow's test data. It
 * follows the NCERT syllabus and the CBSE board question styles (MCQ,
 * assertion–reason, 2/3/5-mark answers, case-based), but nothing is copied from
 * the NCERT textbook or from CBSE papers. Facts are standard syllabus content.
 *
 * Shape (see tests/app/staging-life-processes.test.ts for the invariants):
 *   9 topics · MCQ and assertion–reason (1 mark) · VSA (2) · SA (3) · LA (5)
 *   · case studies (a passage with parts worth 1 + 1 + 2 = 4 marks)
 * That is enough for the full 80-mark CBSE board pattern from this chapter
 * alone, with room to swap, lock, regenerate and print several sets.
 */
import type { Difficulty } from "../../src/server/generator/types";

export const LP_CHAPTER_NUMBER = 5;
export const LP_SOURCE = "Staging · Life Processes (original, CBSE-style)";

export const LP_TOPICS = [
  { slug: "lp-overview", name: "What are life processes" },
  { slug: "lp-autotrophic", name: "Autotrophic nutrition" },
  { slug: "lp-heterotrophic", name: "Heterotrophic nutrition" },
  { slug: "lp-digestion", name: "Nutrition in human beings" },
  { slug: "lp-respiration", name: "Respiration" },
  { slug: "lp-transport-human", name: "Transportation in human beings" },
  { slug: "lp-transport-plant", name: "Transportation in plants" },
  { slug: "lp-excretion-human", name: "Excretion in human beings" },
  { slug: "lp-excretion-plant", name: "Excretion in plants" },
] as const;

export type LpTopic = (typeof LP_TOPICS)[number]["slug"];

export interface LpQuestion {
  topic: LpTopic;
  type: "mcq" | "assertion_reason" | "vsa" | "sa" | "la";
  marks: number;
  difficulty: Difficulty;
  body: string;
  options: { key: string; text: string }[] | null;
  correct: string | null;
  answer: string;
  solution: string;
  rubric: string | null;
  shufflable: boolean;
}

export interface LpCasePart {
  label: string;
  marks: number;
  body: string;
  answer: string;
  solution: string;
}

export interface LpCase {
  key: string;
  topic: LpTopic;
  difficulty: Difficulty;
  passage: string;
  parts: LpCasePart[];
}

const E: Difficulty = "easy";
const M: Difficulty = "medium";
const H: Difficulty = "hard";

function mcq(topic: LpTopic, difficulty: Difficulty, body: string, opts: [string, string, string, string], correct: "A" | "B" | "C" | "D", why: string): LpQuestion {
  const options = (["A", "B", "C", "D"] as const).map((key, i) => ({ key, text: opts[i]! }));
  const text = opts[["A", "B", "C", "D"].indexOf(correct)]!;
  return { topic, type: "mcq", marks: 1, difficulty, body, options, correct, answer: `(${correct}) ${text}`, solution: why, rubric: null, shufflable: true };
}

const AR_OPTIONS = [
  { key: "A", text: "Both Assertion (A) and Reason (R) are true, and R is the correct explanation of A." },
  { key: "B", text: "Both Assertion (A) and Reason (R) are true, but R is not the correct explanation of A." },
  { key: "C", text: "Assertion (A) is true, but Reason (R) is false." },
  { key: "D", text: "Assertion (A) is false, but Reason (R) is true." },
];

function ar(topic: LpTopic, difficulty: Difficulty, assertion: string, reason: string, correct: "A" | "B" | "C" | "D", why: string): LpQuestion {
  return {
    topic,
    type: "assertion_reason",
    marks: 1,
    difficulty,
    // plain text: question bodies are rendered as text + maths, not markdown
    body: `Assertion (A): ${assertion} Reason (R): ${reason}`,
    options: AR_OPTIONS,
    correct,
    answer: `(${correct}) ${AR_OPTIONS.find((o) => o.key === correct)!.text}`,
    solution: why,
    rubric: null,
    // the four assertion–reason options have a fixed meaning and order
    shufflable: false,
  };
}

function written(type: "vsa" | "sa" | "la", marks: number) {
  return (topic: LpTopic, difficulty: Difficulty, body: string, answer: string, rubric: string, solution?: string): LpQuestion => ({
    topic, type, marks, difficulty, body, options: null, correct: null, answer, solution: solution ?? answer, rubric, shufflable: false,
  });
}
const vsa = written("vsa", 2);
const sa = written("sa", 3);
const la = written("la", 5);

// Chemical equations use mhchem, rendered by KaTeX like the maths.
const PHOTO = "$\\ce{6CO2 + 12H2O ->[\\text{sunlight}][\\text{chlorophyll}] C6H12O6 + 6O2 + 6H2O}$";

export const LP_QUESTIONS: LpQuestion[] = [
  // ─────────────────────────── What are life processes ───────────────────────────
  mcq("lp-overview", E, "The process by which an organism takes in food and uses it for energy and body-building is called",
    ["respiration", "nutrition", "excretion", "transportation"], "B",
    "Nutrition is the intake of food and its use as a source of energy and raw material for growth and repair."),
  mcq("lp-overview", E, "Which life process releases energy from food inside the cells?",
    ["Digestion", "Transpiration", "Respiration", "Egestion"], "C",
    "Respiration oxidises food (such as glucose) in cells to release energy, stored as ATP."),
  mcq("lp-overview", M, "Why are maintenance processes needed even when an organism appears to be doing nothing, such as while sleeping?",
    ["Only to allow growth in size", "To prevent damage and breakdown of body structures", "Only to produce heat", "To stop all movement of molecules"], "B",
    "Living structures are constantly being broken down; maintenance and repair need energy at all times, even during rest."),
  mcq("lp-overview", M, "In a large multicellular organism, diffusion alone cannot supply oxygen to all cells because",
    ["cells do not need oxygen", "most cells are not in direct contact with the surroundings", "oxygen cannot diffuse through water", "diffusion only works in plants"], "B",
    "Diffusion is too slow over long distances; in large bodies most cells are far from the surface, so specialised organs and transport systems are needed."),
  mcq("lp-overview", H, "Which pair of life processes is directly concerned with moving materials within the body and removing harmful by-products?",
    ["Nutrition and respiration", "Transportation and excretion", "Respiration and excretion", "Nutrition and transportation"], "B",
    "Transportation carries materials to and from cells; excretion removes harmful metabolic wastes."),
  ar("lp-overview", M, "Unicellular organisms do not need specialised organs for taking in oxygen.",
    "The entire surface of a unicellular organism is in contact with its environment.", "A",
    "Both are true, and the large surface-to-volume contact with the environment is exactly why simple diffusion is enough."),
  ar("lp-overview", H, "Movement is always an indicator of life.",
    "Molecular movements inside cells continue even when an organism is not visibly moving.", "D",
    "The assertion is false: visible movement is not a reliable test (plants hardly move, and wind moves non-living things). The reason is true: molecular movement never stops in living cells."),
  vsa("lp-overview", E, "Name any four life processes.",
    "Nutrition, respiration, transportation and excretion.",
    "½ mark for each correct process (any four of: nutrition, respiration, transportation, excretion)."),
  vsa("lp-overview", M, "Why is energy needed by an organism even when it is resting? Give two reasons.",
    "Energy is needed to maintain and repair body structures that are constantly breaking down, and to keep up processes such as the heartbeat, breathing and maintaining body temperature.",
    "1 mark: maintenance/repair of structures. 1 mark: any ongoing process (heartbeat, breathing, body temperature, cell activity)."),
  vsa("lp-overview", H, "Explain why larger multicellular organisms need a transport system while unicellular organisms do not.",
    "In unicellular organisms every part of the cell is close to the surroundings, so materials move by diffusion. In large organisms most cells are far from the surface, and diffusion over such distances is too slow, so a transport system is needed to carry food, oxygen and wastes.",
    "1 mark: unicellular — whole surface in contact, diffusion enough. 1 mark: multicellular — distance too great, diffusion too slow, so a transport system is required."),
  sa("lp-overview", M, "What criteria do we use to decide whether something is alive? Why is visible movement alone not a good criterion?",
    "Living things carry out life processes: nutrition, respiration, transportation, excretion, growth and reproduction, with constant molecular movement inside cells. Visible movement alone is not a good criterion because many living things, such as trees, show little visible movement, while non-living things, such as leaves blown by the wind, can move.",
    "1 mark: life processes as the criterion. 1 mark: molecular movement / maintenance inside cells. 1 mark: why visible movement fails, with an example."),
  sa("lp-overview", H, "“The outside of a leaf may look still, but its cells are busy.” Justify this statement with reference to three life processes.",
    "Inside the leaf, cells carry out photosynthesis (making food from carbon dioxide and water using sunlight), respiration (breaking down food to release energy) and transpiration/exchange of gases through stomata. Materials are also moved in and out through the xylem and phloem. So many life processes continue even though no visible movement is seen.",
    "1 mark each for any three processes correctly linked to the leaf (photosynthesis, respiration, gaseous exchange/transpiration, transport in xylem/phloem)."),

  // ─────────────────────────── Autotrophic nutrition ───────────────────────────
  mcq("lp-autotrophic", E, "The raw materials for photosynthesis are",
    ["oxygen and glucose", "carbon dioxide and water", "carbon dioxide and glucose", "oxygen and water"], "B",
    "Plants use carbon dioxide from the air and water from the soil, in the presence of sunlight and chlorophyll."),
  mcq("lp-autotrophic", E, "Tiny pores on the surface of leaves through which gases are exchanged are called",
    ["lenticels", "stomata", "alveoli", "villi"], "B",
    "Stomata are pores on leaves, each bordered by two guard cells, used for exchange of gases and loss of water vapour."),
  mcq("lp-autotrophic", M, "The opening and closing of a stoma is controlled by",
    ["the xylem vessels", "the guard cells", "the root hairs", "the phloem"], "B",
    "Guard cells swell when water flows into them, opening the pore, and shrink when they lose water, closing it."),
  mcq("lp-autotrophic", M, "A plant was kept in darkness for 48 hours before a photosynthesis experiment. This was done to",
    ["make the leaves greener", "remove the starch already present in the leaves", "increase the carbon dioxide in the leaves", "kill the guard cells"], "B",
    "In the dark the plant uses up its stored starch, so any starch found after the experiment must have been made during it (destarching)."),
  mcq("lp-autotrophic", M, "When iodine solution is added to a leaf that has been boiled in alcohol after being kept in sunlight, the leaf turns",
    ["red", "blue-black", "green", "yellow"], "B",
    "Starch gives a blue-black colour with iodine; its presence shows that photosynthesis took place."),
  mcq("lp-autotrophic", H, "Desert plants take in carbon dioxide at night rather than during the day mainly to",
    ["avoid water loss through open stomata in the heat of the day", "photosynthesise at night", "release oxygen at night", "absorb more sunlight"], "A",
    "Keeping stomata closed in the hot day reduces water loss; the CO₂ taken in at night is stored and used for photosynthesis in daylight."),
  mcq("lp-autotrophic", H, "In plants, the oxygen released during photosynthesis comes from",
    ["carbon dioxide", "glucose", "water", "chlorophyll"], "C",
    "During the light reactions water is split into hydrogen and oxygen; the oxygen is released as a by-product."),
  ar("lp-autotrophic", E, "Plants store carbohydrates in the form of starch.",
    "Starch is an internal energy reserve that the plant can use when needed.", "A",
    "Both true; starch is the storage form of carbohydrate that is broken down when energy is needed."),
  ar("lp-autotrophic", M, "Leaves of a variegated plant show starch only in the green parts after the iodine test.",
    "Chlorophyll is necessary for photosynthesis.", "A",
    "Only green (chlorophyll-containing) regions photosynthesise and make starch, so R correctly explains A."),
  ar("lp-autotrophic", H, "The stomata of most plants remain open throughout the night.",
    "A stoma opens when its guard cells take in water and swell.", "D",
    "The assertion is false: in most plants stomata close at night, when there is no photosynthesis and no need for carbon dioxide. The reason is true: water entering the guard cells makes them swell and opens the pore."),
  vsa("lp-autotrophic", E, "Write the balanced chemical equation for photosynthesis.",
    PHOTO,
    "1 mark: correct reactants and products. 1 mark: balanced, with sunlight and chlorophyll as conditions."),
  vsa("lp-autotrophic", M, "What are the three main events that occur during photosynthesis?",
    "(i) Absorption of light energy by chlorophyll. (ii) Conversion of light energy to chemical energy and splitting of water into hydrogen and oxygen. (iii) Reduction of carbon dioxide to carbohydrates.",
    "Any two events correct: 1 mark each."),
  vsa("lp-autotrophic", M, "How do guard cells regulate the opening and closing of stomatal pores?",
    "When water flows into the guard cells they swell and curve, opening the pore. When they lose water they shrink and the pore closes.",
    "1 mark: swelling when water enters opens the pore. 1 mark: shrinking when water leaves closes it."),
  vsa("lp-autotrophic", H, "Plants need nitrogen to make proteins. From where and in what form do they obtain it?",
    "From the soil, as inorganic nitrates or nitrites; some plants obtain it as organic compounds prepared by bacteria (for example in the root nodules of legumes).",
    "1 mark: from the soil. 1 mark: as nitrates/nitrites (or organic compounds from bacteria)."),
  sa("lp-autotrophic", M, "Describe an experiment to show that chlorophyll is necessary for photosynthesis.",
    "Take a potted plant with variegated leaves (green and white patches). Keep it in the dark for about three days to remove starch. Then place it in sunlight for about six hours. Pluck a leaf, trace its green areas, boil it in water and then in alcohol to remove chlorophyll, wash it and add iodine solution. Only the parts that were green turn blue-black, showing starch was made only where chlorophyll was present.",
    "1 mark: variegated leaf + destarching. 1 mark: exposure to light and decolourising in alcohol. 1 mark: iodine test result and conclusion."),
  sa("lp-autotrophic", M, "Distinguish between autotrophic and heterotrophic nutrition, giving one example of each.",
    "Autotrophic: the organism makes its own food from simple inorganic substances (CO₂ and water) using sunlight — for example green plants. Heterotrophic: the organism depends on food made by other organisms — for example animals and fungi.",
    "1 mark: definition of autotrophic. 1 mark: definition of heterotrophic. 1 mark: correct example of each."),
  sa("lp-autotrophic", H, "A student covers part of a destarched leaf with black paper on both sides and leaves the plant in sunlight. What result would the iodine test show, and what does it prove? Why was the plant destarched first?",
    "The covered part stays brown/yellowish (no starch) while the uncovered part turns blue-black. This proves that light is necessary for photosynthesis. The plant was destarched so that any starch detected must have been made during the experiment, not stored earlier.",
    "1 mark: correct result for both regions. 1 mark: light is necessary. 1 mark: reason for destarching."),
  la("lp-autotrophic", M, "(a) What is photosynthesis? Write its balanced equation. (b) List the three events that take place during photosynthesis. (c) Why do desert plants open their stomata at night?",
    `(a) Photosynthesis is the process by which green plants make carbohydrates from carbon dioxide and water in the presence of sunlight and chlorophyll, releasing oxygen. ${PHOTO} (b) Absorption of light by chlorophyll; conversion of light energy to chemical energy and splitting of water into hydrogen and oxygen; reduction of CO₂ to carbohydrates. (c) To reduce water loss: they take in CO₂ at night when it is cooler, store it as an intermediate, and use it in photosynthesis during the day.`,
    "(a) 1 mark definition + 1 mark equation. (b) 1½ marks, ½ per event. (c) 1½ marks: water conservation + CO₂ stored at night for daytime use."),
  la("lp-autotrophic", H, "(a) Describe an experiment to show that carbon dioxide is essential for photosynthesis. (b) Explain the role of stomata in this process. (c) Name the substance in which excess glucose is stored in plants.",
    "(a) Take two destarched potted plants. Cover each with a bell jar on a glass plate, sealing the base with vaseline. Place a watch glass of potassium hydroxide (which absorbs CO₂) under one jar. Keep both in sunlight for a few hours, then test a leaf from each with iodine. The leaf from the jar without KOH turns blue-black; the leaf from the jar with KOH does not, showing CO₂ is essential. (b) Stomata are the pores through which CO₂ enters the leaf; they open when guard cells take in water. (c) Starch.",
    "(a) 3 marks: set-up with KOH as CO₂ absorber (1), control (1), observation and conclusion (1). (b) 1 mark. (c) 1 mark."),

  // ─────────────────────────── Heterotrophic nutrition ───────────────────────────
  mcq("lp-heterotrophic", E, "Fungi such as bread mould obtain nutrition by",
    ["photosynthesis", "breaking down food outside the body and absorbing it", "engulfing food using pseudopodia", "feeding on living hosts only"], "B",
    "Saprophytes like bread mould, yeast and mushrooms secrete enzymes onto dead matter and absorb the digested food."),
  mcq("lp-heterotrophic", E, "Amoeba captures its food using",
    ["cilia", "pseudopodia", "tentacles", "flagella"], "B",
    "Amoeba surrounds food with temporary finger-like extensions (pseudopodia), forming a food vacuole."),
  mcq("lp-heterotrophic", M, "Which of the following is a parasitic plant?",
    ["Cuscuta (amarbel)", "Mushroom", "Mango tree", "Yeast"], "A",
    "Cuscuta has no chlorophyll and draws nutrition from the host plant on which it grows."),
  mcq("lp-heterotrophic", M, "In Paramecium, food is moved to a specific spot on the cell by",
    ["pseudopodia", "cilia", "a food vacuole alone", "the nucleus"], "B",
    "Paramecium has a definite shape; cilia covering its surface sweep food into a specific opening."),
  mcq("lp-heterotrophic", H, "Which pair of organisms shows parasitic nutrition?",
    ["Lice and tapeworm", "Mushroom and yeast", "Amoeba and Paramecium", "Grass and cow"], "A",
    "Lice and tapeworms derive nutrition from living hosts without killing them immediately."),
  ar("lp-heterotrophic", M, "Saprophytes help in cleaning the environment.",
    "Saprophytes break down dead and decaying organic matter.", "A",
    "Both true; by decomposing dead matter they recycle nutrients, which explains the cleaning role."),
  ar("lp-heterotrophic", H, "Amoeba takes in food using temporary finger-like extensions of its cell surface.",
    "Amoeba is covered with cilia that sweep food into a fixed opening.", "C",
    "The assertion is true: Amoeba engulfs food with pseudopodia, forming a food vacuole. The reason is false: it is Paramecium that has cilia and a specific spot for taking in food."),
  vsa("lp-heterotrophic", E, "What are saprophytes? Give two examples.",
    "Organisms that obtain nutrition from dead and decaying organic matter by breaking it down outside the body and absorbing it. Examples: bread mould, mushroom, yeast.",
    "1 mark: definition. 1 mark: two correct examples."),
  vsa("lp-heterotrophic", M, "How does Paramecium obtain its food?",
    "Paramecium has a definite shape. Cilia covering its body beat to move food particles to a specific spot (the oral groove), where the food is taken in and enclosed in a food vacuole for digestion.",
    "1 mark: cilia move food. 1 mark: food taken in at a specific spot / food vacuole."),
  vsa("lp-heterotrophic", H, "Name the mode of nutrition of Cuscuta and of a tapeworm. Why is it called so?",
    "Both are parasites: they obtain nutrition from a living host organism, usually harming it, without killing it immediately.",
    "1 mark: parasitic for both. 1 mark: correct explanation."),
  sa("lp-heterotrophic", M, "Describe with a labelled sequence the steps by which Amoeba obtains nutrition.",
    "(i) Ingestion: Amoeba pushes out pseudopodia around the food particle, which fuse to form a food vacuole. (ii) Digestion: enzymes in the food vacuole break food into simple substances. (iii) Absorption and assimilation: digested food diffuses into the cytoplasm and is used. (iv) Egestion: undigested material is thrown out at the cell surface.",
    "½ mark each for ingestion, digestion, absorption, assimilation, egestion (any four = 2 marks) + 1 mark for correct sequence/diagram description."),
  sa("lp-heterotrophic", H, "Compare saprophytic and parasitic nutrition on the basis of (i) source of food (ii) effect on the source (iii) one example each.",
    "(i) Saprophytic: dead and decaying matter; parasitic: a living host. (ii) Saprophytes help decompose waste; parasites harm the host. (iii) Saprophyte: mushroom/bread mould; parasite: Cuscuta/tapeworm/lice.",
    "1 mark for each point of comparison."),
  la("lp-heterotrophic", M, "(a) What is heterotrophic nutrition? (b) Describe three types of heterotrophic nutrition with one example each. (c) How is nutrition in Amoeba different from that in Paramecium?",
    "(a) Nutrition in which organisms depend on food made by others. (b) Holozoic — whole food is taken in and digested inside the body (humans, Amoeba). Saprophytic — food is broken down outside the body and absorbed (fungi). Parasitic — nutrition from a living host (Cuscuta, tapeworm). (c) Amoeba has no fixed shape and engulfs food anywhere using pseudopodia; Paramecium has a fixed shape and uses cilia to move food to a specific spot.",
    "(a) 1 mark. (b) 3 marks — 1 per type with example. (c) 1 mark."),

  // ─────────────────────────── Nutrition in human beings ───────────────────────────
  mcq("lp-digestion", E, "The enzyme present in saliva acts on",
    ["proteins", "fats", "starch", "vitamins"], "C",
    "Salivary amylase breaks down starch into a simpler sugar (maltose)."),
  mcq("lp-digestion", E, "Bile juice is secreted by the",
    ["pancreas", "stomach", "liver", "gall bladder"], "C",
    "Bile is made in the liver and stored in the gall bladder before release into the small intestine."),
  mcq("lp-digestion", M, "The function of hydrochloric acid in the stomach is to",
    ["digest fats", "create an acidic medium for the action of pepsin", "absorb water", "emulsify fats"], "B",
    "HCl makes the stomach contents acidic, which pepsin needs to digest proteins; it also kills many microbes."),
  mcq("lp-digestion", M, "Finger-like projections on the inner wall of the small intestine are called",
    ["alveoli", "villi", "nephrons", "stomata"], "B",
    "Villi greatly increase the surface area for absorption and are richly supplied with blood vessels."),
  mcq("lp-digestion", M, "Which enzyme of pancreatic juice digests proteins?",
    ["Lipase", "Amylase", "Trypsin", "Pepsin"], "C",
    "Trypsin in pancreatic juice digests proteins; lipase acts on emulsified fats."),
  mcq("lp-digestion", H, "Herbivores such as cows have a longer small intestine than carnivores such as tigers because",
    ["they eat more often", "cellulose in grass takes longer to digest", "they drink more water", "meat is harder to digest"], "B",
    "Plant material rich in cellulose needs more time for digestion, so herbivores have a longer small intestine."),
  mcq("lp-digestion", H, "Which of the following is correctly matched?",
    ["Pepsin — fats", "Lipase — fats", "Trypsin — starch", "Amylase — proteins"], "B",
    "Lipase breaks down fats into fatty acids and glycerol; the other pairs are mismatched."),
  ar("lp-digestion", E, "Mucus is secreted by the gastric glands.",
    "Mucus protects the inner lining of the stomach from the action of hydrochloric acid.", "A",
    "Both true and R explains why the mucus is secreted."),
  ar("lp-digestion", M, "Bile juice does not contain any digestive enzyme.",
    "Bile salts break large fat globules into smaller droplets, increasing the efficiency of enzyme action.", "B",
    "Both statements are true, but R describes the function of bile (emulsification), not the reason it lacks enzymes."),
  ar("lp-digestion", H, "Food moves through the alimentary canal even when a person is lying down.",
    "Rhythmic contraction of the muscles lining the gut (peristalsis) pushes food forward.", "A",
    "Both true; peristalsis, not gravity, moves food, which explains A."),
  vsa("lp-digestion", E, "What is the role of the teeth and the tongue in digestion?",
    "Teeth crush and grind food into smaller pieces. The tongue mixes food with saliva and helps push it towards the throat for swallowing.",
    "1 mark: teeth — breaking food. 1 mark: tongue — mixing and swallowing."),
  vsa("lp-digestion", M, "What is peristalsis? Where does it occur?",
    "Peristalsis is the rhythmic contraction and relaxation of the muscles of the alimentary canal that pushes food forward. It occurs along the whole gut, beginning in the oesophagus.",
    "1 mark: definition. 1 mark: location."),
  vsa("lp-digestion", M, "State two functions of the liver in digestion.",
    "It secretes bile juice, which makes the food coming from the stomach alkaline so pancreatic enzymes can act, and which emulsifies fats into small droplets.",
    "1 mark: alkaline medium. 1 mark: emulsification of fats."),
  vsa("lp-digestion", H, "Why is the small intestine the main site for absorption of digested food? Give two reasons.",
    "It is very long, and its inner lining has millions of villi that increase the surface area for absorption; the villi are richly supplied with blood vessels that carry absorbed food to every cell.",
    "1 mark: length/villi increasing surface area. 1 mark: rich blood supply."),
  sa("lp-digestion", E, "Name the three secretions of the gastric glands and state the function of each.",
    "Hydrochloric acid: creates an acidic medium for pepsin and kills germs. Pepsin: digests proteins. Mucus: protects the stomach lining from the acid.",
    "1 mark for each secretion with its function."),
  sa("lp-digestion", M, "What is the role of the pancreas in digestion?",
    "The pancreas secretes pancreatic juice into the small intestine. It contains amylase, which breaks down starch; trypsin, which digests proteins; and lipase, which breaks down emulsified fats.",
    "1 mark each for trypsin, lipase and amylase with their substrates."),
  sa("lp-digestion", H, "What are the end products of digestion of carbohydrates, proteins and fats? Where in the gut is digestion of all three completed?",
    "Carbohydrates → glucose; proteins → amino acids; fats → fatty acids and glycerol. Digestion of all three is completed in the small intestine by the intestinal juice.",
    "½ mark per end product (1½). 1½ marks: small intestine / intestinal juice."),
  la("lp-digestion", E, "Draw a labelled diagram of the human alimentary canal. Label the mouth, oesophagus, stomach, liver, pancreas, small intestine and large intestine. State the function of any two labelled parts.",
    "Diagram of the alimentary canal with the seven labels. Functions, for example: stomach — digests proteins with pepsin in an acidic medium; small intestine — completes digestion and absorbs digested food through villi; liver — secretes bile; large intestine — absorbs water.",
    "3 marks: diagram with correct labels (½ mark per label, rounding). 2 marks: two correct functions."),
  la("lp-digestion", M, "Trace the path of a piece of chapati (starch) from the mouth to the blood. Name the enzyme acting at each step and the product formed.",
    "Mouth: salivary amylase breaks starch into maltose. Oesophagus: moved by peristalsis (no digestion). Stomach: no starch digestion (acidic medium). Small intestine: pancreatic amylase continues starch breakdown; intestinal juice converts remaining sugars into glucose. Glucose is absorbed through the villi into the blood capillaries.",
    "1 mark each: mouth; oesophagus/stomach; pancreatic amylase; intestinal juice to glucose; absorption by villi."),
  la("lp-digestion", H, "(a) Explain the role of bile in the digestion of fats. (b) What would happen to fat digestion if the bile duct were blocked? (c) How are the digested products of fats absorbed?",
    "(a) Bile makes the medium alkaline so pancreatic lipase can act, and bile salts emulsify large fat globules into small droplets, increasing their surface area for lipase. (b) Fats would not be emulsified and the medium would stay acidic, so lipase would work poorly; much fat would pass out undigested. (c) Fatty acids and glycerol are absorbed through the villi of the small intestine, largely into the lymph vessels (lacteals).",
    "(a) 2 marks. (b) 2 marks. (c) 1 mark."),

  // ─────────────────────────── Respiration ───────────────────────────
  mcq("lp-respiration", E, "The first step in the breakdown of glucose, common to aerobic and anaerobic respiration, takes place in the",
    ["mitochondria", "cytoplasm", "nucleus", "chloroplast"], "B",
    "Glucose (6 carbon) is broken into pyruvate (3 carbon) in the cytoplasm in both types of respiration."),
  mcq("lp-respiration", E, "The energy currency of the cell is",
    ["ADP", "ATP", "glucose", "pyruvate"], "B",
    "ATP stores energy released in respiration and supplies it to cell activities."),
  mcq("lp-respiration", M, "During vigorous exercise, the muscle cells produce",
    ["ethanol", "lactic acid", "carbon dioxide only", "glucose"], "B",
    "When oxygen runs short, pyruvate is converted to lactic acid in muscle cells, which causes cramps."),
  mcq("lp-respiration", M, "Anaerobic respiration in yeast produces",
    ["lactic acid and energy", "ethanol, carbon dioxide and energy", "carbon dioxide, water and energy", "glucose and oxygen"], "B",
    "In yeast, pyruvate is converted to ethanol and carbon dioxide in the absence of oxygen (fermentation)."),
  mcq("lp-respiration", M, "The rings of cartilage in the trachea",
    ["filter dust from the air", "ensure the air passage does not collapse", "exchange gases", "produce mucus"], "B",
    "The C-shaped cartilage rings keep the windpipe open."),
  mcq("lp-respiration", H, "Aquatic animals breathe much faster than terrestrial animals because",
    ["water is colder than air", "the amount of dissolved oxygen in water is low", "they need less energy", "water contains no oxygen"], "B",
    "Water holds far less dissolved oxygen than air contains, so aquatic organisms must breathe faster to get enough."),
  mcq("lp-respiration", H, "Which of the following correctly shows aerobic respiration?",
    ["Glucose → pyruvate → lactic acid + energy", "Glucose → pyruvate → ethanol + CO₂ + energy", "Glucose → pyruvate → CO₂ + H₂O + energy", "Glucose → ethanol → pyruvate + energy"], "C",
    "In the presence of oxygen, pyruvate is completely broken down in the mitochondria into CO₂ and water, releasing much more energy."),
  ar("lp-respiration", E, "Aerobic respiration releases more energy than anaerobic respiration.",
    "In aerobic respiration glucose is completely broken down into carbon dioxide and water.", "A",
    "Both true; complete oxidation releases far more energy, which explains A."),
  ar("lp-respiration", M, "The alveoli are the site of gaseous exchange in the lungs.",
    "Alveoli have thin walls and a rich network of blood capillaries.", "A",
    "Both true; the thin walls and capillary network make exchange efficient."),
  ar("lp-respiration", H, "In plants, carbon dioxide is released during the day.",
    "During the day, the carbon dioxide produced by respiration is used up in photosynthesis.", "D",
    "The assertion is false: during the day there is net intake of CO₂ (and release of O₂). The reason is true."),
  vsa("lp-respiration", E, "Name the site of (i) the first step of glucose breakdown and (ii) aerobic breakdown of pyruvate.",
    "(i) Cytoplasm. (ii) Mitochondria.",
    "1 mark each."),
  vsa("lp-respiration", M, "Why do we get muscle cramps after running fast for a long time?",
    "The muscles need energy faster than oxygen can be supplied, so they respire anaerobically; pyruvate is converted into lactic acid, and its build-up causes cramps.",
    "1 mark: lack of oxygen / anaerobic respiration. 1 mark: lactic acid accumulation."),
  vsa("lp-respiration", M, "How is the respiratory pigment haemoglobin suited to its function?",
    "Haemoglobin, present in red blood cells, has a very high affinity for oxygen, so it picks up oxygen in the lungs and carries it to tissues where oxygen is in short supply.",
    "1 mark: in RBCs / carries oxygen. 1 mark: high affinity for oxygen."),
  vsa("lp-respiration", H, "Why does the lung always contain some air even after we breathe out fully? What is the advantage?",
    "A residual volume of air always remains in the lungs, so there is enough time for oxygen to be absorbed and carbon dioxide to be released continuously, even between breaths.",
    "1 mark: residual volume. 1 mark: continuous gas exchange."),
  sa("lp-respiration", E, "Differentiate between aerobic and anaerobic respiration on three points.",
    "Aerobic: uses oxygen; anaerobic: without oxygen. Aerobic: end products CO₂ and water; anaerobic: ethanol + CO₂ (yeast) or lactic acid (muscles). Aerobic: releases much more energy; anaerobic: releases less. (Also: aerobic takes place in mitochondria; anaerobic in cytoplasm.)",
    "1 mark for each valid point of difference."),
  sa("lp-respiration", M, "Describe how air enters the lungs during breathing in.",
    "When we breathe in, the ribs are lifted and the diaphragm flattens. This enlarges the chest cavity, lowering the pressure inside, so air is sucked into the lungs and fills the expanded alveoli.",
    "1 mark: ribs move up/out. 1 mark: diaphragm flattens. 1 mark: larger cavity sucks air in."),
  sa("lp-respiration", H, "How do plants exchange gases? Why is their rate of gas exchange lower than in animals?",
    "Plants exchange gases by diffusion through stomata in leaves and lenticels in stems and roots. The direction depends on conditions: at night CO₂ is given out; during the day CO₂ from respiration is used in photosynthesis, so O₂ is released. Plant cells respire slowly and have no active movement, so their energy needs and rate of gas exchange are lower than those of animals.",
    "1 mark: diffusion through stomata/lenticels. 1 mark: day vs night direction. 1 mark: lower energy needs."),
  la("lp-respiration", M, "(a) Draw a flow chart showing the breakdown of glucose by various pathways. (b) Where does each pathway occur? (c) Which pathway gives the most energy, and why?",
    "(a) Glucose (6C) → pyruvate (3C) + energy [in cytoplasm]. Then: (i) no oxygen, in yeast → ethanol + CO₂ + energy; (ii) lack of oxygen, in muscle cells → lactic acid + energy; (iii) oxygen present, in mitochondria → CO₂ + H₂O + energy. (b) Glucose to pyruvate: cytoplasm; anaerobic steps: cytoplasm; aerobic step: mitochondria. (c) Aerobic respiration, because glucose is completely oxidised to CO₂ and water.",
    "(a) 3 marks: three pathways with correct products. (b) 1 mark. (c) 1 mark."),
  la("lp-respiration", H, "(a) Describe the path of air from the nostrils to the alveoli. (b) How are the lungs designed to maximise the area for exchange of gases? (c) How are oxygen and carbon dioxide transported in human beings?",
    "(a) Nostrils (hairs and mucus filter the air) → pharynx → larynx → trachea (kept open by rings of cartilage) → bronchi → bronchioles → alveoli. (b) The lungs contain millions of balloon-like alveoli; if spread out they would cover about 80 m². Their walls are thin and surrounded by a dense network of capillaries. (c) Oxygen is carried by haemoglobin in red blood cells; carbon dioxide, being more soluble in water, is mostly carried dissolved in the blood plasma.",
    "(a) 2 marks. (b) 1½ marks. (c) 1½ marks."),

  // ─────────────────────────── Transportation in human beings ───────────────────────────
  mcq("lp-transport-human", E, "Which chamber of the human heart pumps oxygenated blood to the rest of the body?",
    ["Right atrium", "Right ventricle", "Left atrium", "Left ventricle"], "D",
    "The left ventricle pumps oxygenated blood into the aorta and so to the whole body."),
  mcq("lp-transport-human", E, "Blood vessels that carry blood away from the heart are called",
    ["veins", "arteries", "capillaries", "lymph vessels"], "B",
    "Arteries carry blood away from the heart under high pressure."),
  mcq("lp-transport-human", M, "Valves in the heart and veins",
    ["speed up blood flow", "prevent the backflow of blood", "clot the blood", "carry oxygen"], "B",
    "Valves ensure blood flows only in one direction."),
  mcq("lp-transport-human", M, "The normal blood pressure of a healthy adult is about",
    ["80/120 mm Hg", "120/80 mm Hg", "200/100 mm Hg", "60/40 mm Hg"], "B",
    "Systolic pressure is about 120 mm Hg and diastolic about 80 mm Hg."),
  mcq("lp-transport-human", M, "Which blood cells help to plug leaks at the site of an injury?",
    ["Red blood cells", "White blood cells", "Platelets", "Plasma cells"], "C",
    "Platelets circulate in the blood and help blood to clot at a wound."),
  mcq("lp-transport-human", H, "Lymph differs from blood plasma in that lymph",
    ["contains more proteins", "is red in colour", "contains less protein and carries absorbed fat", "contains haemoglobin"], "C",
    "Lymph is colourless, has less protein than plasma, and carries fat absorbed from the intestine."),
  mcq("lp-transport-human", H, "Fish have a two-chambered heart. As a result, blood in fish",
    ["passes through the heart twice in each cycle", "passes through the heart only once in each cycle", "never reaches the gills", "is always deoxygenated"], "B",
    "Blood is pumped to the gills, oxygenated, and goes straight to the body — single circulation."),
  ar("lp-transport-human", E, "The walls of the ventricles are thicker than those of the atria.",
    "Ventricles have to pump blood into various organs.", "A",
    "Both true; ventricles pump blood to distant organs and need more force, which explains their thick walls."),
  ar("lp-transport-human", M, "Birds and mammals need a four-chambered heart.",
    "Separating oxygenated and deoxygenated blood gives an efficient oxygen supply for their high energy needs, including maintaining body temperature.", "A",
    "Both true; R correctly explains the need."),
  ar("lp-transport-human", H, "Arteries have thin, non-elastic walls.",
    "Blood in the arteries flows under high pressure.", "D",
    "The assertion is false: arteries have thick, elastic walls. The reason is true, and is why their walls are thick."),
  vsa("lp-transport-human", E, "Name the components of the transport system in human beings and state one function of each.",
    "Heart — pumps blood. Blood vessels — carry blood around the body. Blood — carries oxygen, food, wastes and hormones. (Any two components with functions.)",
    "1 mark each for two components with correct functions."),
  vsa("lp-transport-human", M, "What is meant by double circulation?",
    "Blood passes through the heart twice during each complete cycle: once in the pulmonary circuit (heart → lungs → heart) and once in the systemic circuit (heart → body → heart).",
    "1 mark: passes through the heart twice. 1 mark: pulmonary and systemic circuits."),
  vsa("lp-transport-human", M, "State two functions of lymph.",
    "It carries digested and absorbed fat from the intestine, and it drains excess tissue fluid from intercellular spaces back into the blood.",
    "1 mark each."),
  vsa("lp-transport-human", H, "Why are the walls of capillaries only one cell thick?",
    "So that materials such as oxygen, food and wastes can be exchanged easily between the blood and the surrounding cells by diffusion.",
    "1 mark: exchange between blood and cells. 1 mark: diffusion made easy by thin walls."),
  sa("lp-transport-human", E, "Differentiate between arteries and veins on three points.",
    "Arteries carry blood away from the heart; veins carry it to the heart. Arteries have thick elastic walls; veins have thin walls. Arteries have no valves (except at their base); veins have valves. (Also: arteries carry blood under high pressure, veins under low pressure.)",
    "1 mark for each valid point."),
  sa("lp-transport-human", M, "What is blood pressure? How is it measured, and what are systolic and diastolic pressure?",
    "Blood pressure is the force that blood exerts against the wall of a vessel. It is measured with a sphygmomanometer. Systolic pressure (about 120 mm Hg) is the pressure in the artery during ventricular contraction; diastolic pressure (about 80 mm Hg) is the pressure during ventricular relaxation.",
    "1 mark: definition. 1 mark: instrument. 1 mark: systolic and diastolic with values."),
  sa("lp-transport-human", H, "Why is it necessary to separate oxygenated and deoxygenated blood in mammals and birds? How do amphibians manage with a three-chambered heart?",
    "Mammals and birds are warm-blooded and have high energy needs; separating the two kinds of blood gives a highly efficient supply of oxygen to the body. Amphibians and many reptiles have lower energy needs and a body temperature that depends on the surroundings, so some mixing of blood in their three-chambered heart can be tolerated.",
    "1½ marks: high energy / body temperature / efficient oxygen supply. 1½ marks: amphibians tolerate mixing because of lower energy needs."),
  la("lp-transport-human", E, "Draw a labelled diagram of the sectional view of the human heart and describe the flow of blood through it.",
    "Diagram showing the four chambers, vena cava, pulmonary artery, pulmonary veins, aorta and valves. Deoxygenated blood from the body enters the right atrium through the vena cava → right ventricle → pulmonary artery → lungs. Oxygenated blood returns through the pulmonary veins → left atrium → left ventricle → aorta → body.",
    "2½ marks: diagram with labels. 2½ marks: correct sequence of blood flow."),
  la("lp-transport-human", M, "(a) Describe double circulation in human beings with a flow diagram. (b) Why is it important? (c) How does it differ from circulation in fish?",
    "(a) Body → vena cava → right atrium → right ventricle → pulmonary artery → lungs (oxygenated) → pulmonary veins → left atrium → left ventricle → aorta → body. Blood passes through the heart twice per cycle. (b) It keeps oxygenated and deoxygenated blood separate, giving an efficient oxygen supply for high energy needs and a constant body temperature. (c) Fish have a two-chambered heart and single circulation: blood goes from the heart to the gills and then directly to the body, passing through the heart only once per cycle.",
    "(a) 2½ marks. (b) 1½ marks. (c) 1 mark."),
  la("lp-transport-human", H, "(a) Explain the composition and functions of blood. (b) What is lymph and how is it formed? (c) What would happen if platelets were absent from the blood?",
    "(a) Blood has a fluid medium, plasma, which carries food, CO₂ and nitrogenous wastes in dissolved form; red blood cells carry oxygen using haemoglobin; white blood cells fight infection; platelets help clotting. (b) Lymph is a colourless fluid formed when some plasma, proteins and blood cells escape through the pores in capillary walls into the intercellular spaces; it flows through lymphatic capillaries into larger vessels that join the veins. (c) Blood would not clot at an injury, so bleeding would continue and could be dangerous.",
    "(a) 2 marks. (b) 2 marks. (c) 1 mark."),

  // ─────────────────────────── Transportation in plants ───────────────────────────
  mcq("lp-transport-plant", E, "Water and minerals are transported in plants by",
    ["phloem", "xylem", "stomata", "cambium"], "B",
    "Xylem carries water and dissolved minerals from the roots to the rest of the plant."),
  mcq("lp-transport-plant", E, "The loss of water in the form of vapour from the aerial parts of a plant is called",
    ["translocation", "transpiration", "respiration", "guttation"], "B",
    "Transpiration is the evaporation of water mainly through the stomata of leaves."),
  mcq("lp-transport-plant", M, "Transport of soluble products of photosynthesis in plants is called",
    ["transpiration", "translocation", "absorption", "diffusion"], "B",
    "Translocation is the movement of food (mainly sucrose) through the phloem."),
  mcq("lp-transport-plant", M, "Movement of water in the xylem during the day is mainly due to",
    ["root pressure", "transpiration pull", "gravity", "active transport in phloem"], "B",
    "During the day, evaporation from leaves creates a suction that pulls water up the xylem."),
  mcq("lp-transport-plant", H, "Translocation of food in the phloem requires",
    ["no energy at all", "energy from ATP", "sunlight directly", "transpiration pull"], "B",
    "Sucrose is loaded into phloem using ATP; the resulting osmotic pressure moves material through the phloem."),
  mcq("lp-transport-plant", H, "Which statement about translocation is correct?",
    ["It occurs only upwards", "It occurs only downwards", "It can occur both upwards and downwards", "It occurs only in xylem"], "C",
    "Food moves to wherever it is needed — for example, from storage organs up to growing buds in spring."),
  ar("lp-transport-plant", E, "Transpiration helps in the upward movement of water in plants.",
    "Loss of water from leaves creates a suction force that pulls water up through the xylem.", "A",
    "Both true; the transpiration pull explains the upward movement."),
  ar("lp-transport-plant", M, "Root pressure is especially important for water movement at night.",
    "At night, stomata are generally closed and transpiration pull is weak.", "A",
    "Both true; with little transpiration at night, root pressure becomes the main force."),
  vsa("lp-transport-plant", E, "Name the two conducting tissues in plants and what each transports.",
    "Xylem transports water and minerals; phloem transports food (products of photosynthesis).",
    "1 mark each."),
  vsa("lp-transport-plant", M, "How do root cells take up water from the soil?",
    "Root cells actively take up ions from the soil, creating a difference in ion concentration between the root and the soil. Water then moves into the root from the soil to remove this difference, creating a steady flow into the xylem.",
    "1 mark: active uptake of ions. 1 mark: water follows the concentration difference."),
  vsa("lp-transport-plant", M, "Give two functions of transpiration.",
    "It helps in the upward movement of water and minerals from roots to leaves, and it helps regulate the temperature of the plant.",
    "1 mark each."),
  vsa("lp-transport-plant", H, "Why does a plant need a separate transport system for water and for food?",
    "Water and minerals come from the soil and must move up from the roots, while food is made in the leaves and must move to all parts, both up and down; the two need different mechanisms (transpiration pull versus energy-driven translocation), so separate tissues, xylem and phloem, are used.",
    "1 mark: different sources and directions. 1 mark: different mechanisms — xylem and phloem."),
  sa("lp-transport-plant", E, "Differentiate between xylem and phloem on three points.",
    "Xylem carries water and minerals; phloem carries food. Xylem transport is mostly upwards; phloem transport is both up and down. Xylem movement is by transpiration pull and root pressure (little energy used); phloem translocation uses energy from ATP.",
    "1 mark for each point."),
  sa("lp-transport-plant", M, "Explain how transpiration pull moves water to the top of a tall tree.",
    "Water evaporates from the leaf cells through the stomata. The lost water is replaced by water from the xylem in the leaf, which creates a suction. Because water molecules stick together, this suction pulls a continuous column of water up through the xylem from the roots to the leaves.",
    "1 mark: evaporation through stomata. 1 mark: suction created in leaf xylem. 1 mark: continuous column pulled up."),
  sa("lp-transport-plant", H, "Describe the process of translocation. Why is energy needed for it?",
    "Translocation is the transport of soluble products of photosynthesis, mainly sucrose, through the phloem, along with amino acids and other substances, to storage organs, fruits, seeds and growing parts. Sucrose is transferred into the phloem using energy from ATP. This raises the osmotic pressure, drawing water in, and the pressure moves material to areas of lower pressure where it is needed.",
    "1 mark: definition and substances. 1 mark: ATP-driven loading. 1 mark: osmotic pressure moves material."),
  la("lp-transport-plant", M, "(a) Describe the transport of water and minerals in plants. (b) What is the role of transpiration? (c) How does water movement at night differ from that during the day?",
    "(a) Xylem vessels and tracheids of roots, stems and leaves are connected into a continuous system. Root cells take up ions actively, so water moves in from the soil and is pushed into the xylem. (b) Transpiration — evaporation through the stomata — creates a suction that pulls water up the xylem, helps absorb and move minerals, and helps regulate temperature. (c) During the day, transpiration pull is the main force; at night, when stomata are mostly closed, root pressure is more important.",
    "(a) 2 marks. (b) 2 marks. (c) 1 mark."),

  // ─────────────────────────── Excretion in human beings ───────────────────────────
  mcq("lp-excretion-human", E, "The basic filtration unit of the kidney is the",
    ["neuron", "nephron", "alveolus", "villus"], "B",
    "Each kidney has a large number of nephrons, which filter the blood."),
  mcq("lp-excretion-human", E, "Urine is carried from the kidneys to the urinary bladder by the",
    ["urethra", "ureters", "renal artery", "renal vein"], "B",
    "Each kidney is connected to the bladder by a ureter."),
  mcq("lp-excretion-human", M, "The cup-shaped structure at the start of a nephron that holds the glomerulus is",
    ["Bowman's capsule", "the collecting duct", "the loop of the tubule", "the ureter"], "A",
    "Bowman's capsule surrounds the glomerulus and collects the filtrate."),
  mcq("lp-excretion-human", M, "Which of these is reabsorbed from the tubules of the nephron?",
    ["Urea only", "Glucose, amino acids, salts and water", "Only uric acid", "Blood cells"], "B",
    "Useful substances in the filtrate are selectively reabsorbed as it passes along the tubule."),
  mcq("lp-excretion-human", H, "The main nitrogenous waste excreted by human beings is",
    ["ammonia", "urea", "uric acid", "carbon dioxide"], "B",
    "Humans excrete nitrogen mainly as urea, which the kidneys remove from the blood."),
  mcq("lp-excretion-human", H, "An artificial kidney (haemodialysis) differs from a natural kidney in that",
    ["it filters no urea", "it does not reabsorb useful substances", "it produces more urine", "it works only on plasma proteins"], "B",
    "In dialysis, wastes diffuse out into the dialysing fluid, but there is no reabsorption as in the nephron."),
  ar("lp-excretion-human", M, "The amount of water reabsorbed in the kidney varies from day to day.",
    "It depends on how much excess water there is in the body and how much dissolved waste has to be excreted.", "A",
    "Both true; R explains the variation."),
  ar("lp-excretion-human", H, "The glomerulus filters blood cells and proteins into the Bowman's capsule.",
    "The glomerulus is a cluster of thin-walled blood capillaries.", "D",
    "The assertion is false: blood cells and large proteins are too big to be filtered. The reason is true."),
  vsa("lp-excretion-human", E, "Name the organs of the human excretory system.",
    "A pair of kidneys, a pair of ureters, a urinary bladder and a urethra.",
    "½ mark each."),
  vsa("lp-excretion-human", M, "What is the function of the glomerulus?",
    "The glomerulus is a cluster of capillaries in Bowman's capsule where blood is filtered; water, glucose, salts, amino acids and urea pass into the capsule as filtrate.",
    "1 mark: filtration of blood. 1 mark: what passes into the filtrate."),
  vsa("lp-excretion-human", M, "What is the purpose of making urine?",
    "To filter nitrogenous wastes such as urea and uric acid out of the blood and remove them from the body, while also balancing the amount of water and salts in the body.",
    "1 mark: removal of nitrogenous waste. 1 mark: water/salt balance."),
  vsa("lp-excretion-human", H, "How is the amount of urine produced regulated?",
    "By the amount of water reabsorbed in the tubules, which depends on how much excess water there is in the body and how much dissolved waste has to be excreted; hormones help control this.",
    "1 mark: reabsorption varies. 1 mark: depends on excess water / dissolved waste."),
  sa("lp-excretion-human", E, "Describe the structure of a nephron with the help of a labelled sequence of its parts.",
    "Each nephron begins as a cup-shaped Bowman's capsule holding a cluster of capillaries (the glomerulus). The capsule leads into a long, coiled tubule surrounded by blood capillaries, which opens into a collecting duct that carries urine to the ureter.",
    "1 mark: Bowman's capsule with glomerulus. 1 mark: tubule with capillaries. 1 mark: collecting duct."),
  sa("lp-excretion-human", M, "Explain how urine is formed in the nephron.",
    "(i) Filtration: blood is filtered in the glomerulus and the filtrate enters Bowman's capsule. (ii) Reabsorption: as the filtrate passes along the tubule, useful substances such as glucose, amino acids, salts and a major amount of water are reabsorbed into the surrounding capillaries. (iii) The remaining fluid, containing urea and excess water and salts, is urine; it flows into the collecting duct.",
    "1 mark each for filtration, selective reabsorption and urine collection."),
  sa("lp-excretion-human", H, "About 180 litres of filtrate is formed in the kidneys every day, but only 1 to 2 litres of urine is excreted. Explain.",
    "Most of the filtrate is reabsorbed in the tubules: glucose, amino acids, salts and most of the water are taken back into the blood because the body needs them. Only the waste (mainly urea) with a small amount of water leaves as urine.",
    "1 mark: most of the filtrate is reabsorbed. 1 mark: named useful substances. 1 mark: only wastes with a little water are excreted."),
  la("lp-excretion-human", M, "(a) Draw a labelled diagram of the human excretory system. (b) Describe the structure and function of a nephron. (c) What is haemodialysis and when is it used?",
    "(a) Diagram showing kidneys, renal artery and vein, ureters, urinary bladder and urethra. (b) A nephron has Bowman's capsule containing the glomerulus (filtration) and a tubule where useful substances are reabsorbed, leading to a collecting duct; it filters blood and forms urine. (c) Haemodialysis uses an artificial kidney: blood is passed through long tubes lined with a semi-permeable membrane in a tank of dialysing fluid, and nitrogenous wastes diffuse out. It is used when the kidneys fail (for example from infection, injury or restricted blood flow).",
    "(a) 2 marks. (b) 2 marks. (c) 1 mark."),
  la("lp-excretion-human", H, "Compare the functioning of a natural kidney with an artificial kidney. Why is reabsorption important for the body?",
    "Both remove nitrogenous wastes from the blood. The natural kidney filters blood in the glomerulus and then selectively reabsorbs glucose, amino acids, salts and most of the water in the tubules; its output is regulated by the body's needs. The artificial kidney only removes wastes by diffusion into dialysing fluid, which has the same osmotic pressure as blood but no nitrogenous waste; there is no reabsorption. Reabsorption is important because it saves water and useful substances the body needs, keeping its water and salt balance steady.",
    "2 marks: natural kidney (filtration + reabsorption). 2 marks: artificial kidney (diffusion, no reabsorption). 1 mark: importance of reabsorption."),

  // ─────────────────────────── Excretion in plants ───────────────────────────
  mcq("lp-excretion-plant", E, "Plants get rid of excess water by",
    ["translocation", "transpiration", "photosynthesis", "absorption"], "B",
    "Excess water is lost as vapour through the stomata."),
  mcq("lp-excretion-plant", M, "Resins and gums in plants are stored mainly in",
    ["young leaves", "old xylem", "root hairs", "flowers"], "B",
    "Some waste products are stored as resins and gums, especially in old xylem."),
  mcq("lp-excretion-plant", M, "Some plant wastes are stored in cellular vacuoles or in leaves that",
    ["remain on the plant forever", "fall off", "turn into roots", "become stomata"], "B",
    "Wastes stored in leaves are removed when the leaves fall off."),
  mcq("lp-excretion-plant", H, "Which of the following is NOT a way in which plants deal with wastes?",
    ["Storing them in leaves that fall", "Excreting some into the soil around them", "Storing them as resins in old xylem", "Removing them through a kidney-like organ"], "D",
    "Plants have no special excretory organ; the other three are genuine strategies."),
  ar("lp-excretion-plant", M, "Plants do not have specialised excretory organs like animals.",
    "Plants produce smaller amounts of waste, and many wastes can be stored or lost through leaves and bark.", "A",
    "Both true; the low rate of waste production and storage options explain the lack of special organs."),
  vsa("lp-excretion-plant", E, "Name two waste products of plants and state how each is removed.",
    "Oxygen (from photosynthesis) and carbon dioxide (from respiration) are removed by diffusion through stomata; excess water is lost by transpiration. (Also: resins and gums stored in old xylem.)",
    "1 mark each for a waste and its removal."),
  vsa("lp-excretion-plant", M, "How do plants use the process of shedding leaves to get rid of wastes?",
    "Many wastes are stored in the leaves; when the leaves fall off, the wastes stored in them are removed from the plant.",
    "1 mark: wastes stored in leaves. 1 mark: removed when leaves fall."),
  sa("lp-excretion-plant", M, "List three ways in which plants get rid of their excretory products.",
    "(i) Gaseous wastes (O₂, CO₂) are removed by diffusion through stomata, and excess water by transpiration. (ii) Wastes are stored in vacuoles or in leaves that later fall off. (iii) Wastes are stored as resins and gums in old xylem, and some are excreted into the soil.",
    "1 mark per method."),
  sa("lp-excretion-plant", H, "Compare excretion in plants and in human beings on three points.",
    "Organs: humans have a specialised excretory system (kidneys); plants have none. Main waste: humans excrete urea in urine; plants lose oxygen, CO₂ and water and store other wastes. Method: humans filter blood in nephrons; plants use diffusion, transpiration, storage in leaves, vacuoles and old xylem, and release some into the soil.",
    "1 mark per valid point of comparison."),
];

export const LP_CASES: LpCase[] = [
  {
    key: "digestion-enzymes", topic: "lp-digestion", difficulty: M,
    passage: "Riya ate a meal of rice, dal and ghee. In her mouth, chewing broke the rice into smaller pieces and saliva began to act on it. In her stomach, an acidic secretion mixed with the food and the protein in the dal started to break down. When the food reached her small intestine, bile and pancreatic juice were added to it, and by the end of the small intestine the food had been broken into its simplest forms and absorbed into her blood.",
    parts: [
      { label: "(a)", marks: 1, body: "Name the enzyme in saliva and the food component on which it acts.", answer: "Salivary amylase; it acts on starch (from the rice).", solution: "Salivary amylase begins starch digestion in the mouth, producing maltose." },
      { label: "(b)", marks: 1, body: "Which enzyme begins the digestion of the protein in the dal in the stomach?", answer: "Pepsin.", solution: "Pepsin, secreted by the gastric glands, digests proteins in the acidic medium created by HCl." },
      { label: "(c)", marks: 2, body: "Explain how the ghee (fat) in Riya's meal is digested in the small intestine.", answer: "Bile from the liver makes the medium alkaline and emulsifies the fat into small droplets; lipase in pancreatic juice then breaks the fat down, and intestinal juice completes its conversion into fatty acids and glycerol.", solution: "1 mark: emulsification by bile (and alkaline medium). 1 mark: lipase → fatty acids and glycerol." },
    ],
  },
  {
    key: "villi-absorption", topic: "lp-digestion", difficulty: H,
    passage: "A doctor explained to a patient that the inner lining of the small intestine has millions of tiny finger-like projections. Because of them, the absorbing surface of the small intestine is many times larger than that of a smooth tube of the same length. Each projection has a thin covering and a dense network of blood vessels inside it. In some diseases these projections become flattened, and the patient loses weight even when eating well.",
    parts: [
      { label: "(a)", marks: 1, body: "What are these finger-like projections called?", answer: "Villi.", solution: "Villi line the inner wall of the small intestine." },
      { label: "(b)", marks: 1, body: "Why is a dense network of blood vessels present in each projection?", answer: "To take up the absorbed food and carry it to every cell of the body.", solution: "The blood vessels carry absorbed nutrients away from the intestine to the body cells." },
      { label: "(c)", marks: 2, body: "Explain why a patient whose projections have become flattened loses weight even when eating well.", answer: "Flattened villi greatly reduce the surface area for absorption, so much of the digested food is not absorbed into the blood and passes out; the body does not get enough nutrients, so the person loses weight.", solution: "1 mark: reduced surface area. 1 mark: less absorption → less nutrition → weight loss." },
    ],
  },
  {
    key: "exercise-cramps", topic: "lp-respiration", difficulty: M,
    passage: "During a school sports day, Arjun ran a 400 m race as fast as he could. Near the end his leg muscles began to hurt and he felt cramps. He was breathing very fast and deeply for several minutes after the race. Later that week, his class visited a bakery, where they saw dough rising after yeast was added to it.",
    parts: [
      { label: "(a)", marks: 1, body: "Which substance built up in Arjun's muscles and caused the cramps?", answer: "Lactic acid.", solution: "When oxygen is short, pyruvate is converted into lactic acid in the muscle cells." },
      { label: "(b)", marks: 1, body: "Why did Arjun keep breathing fast and deeply after the race?", answer: "To take in extra oxygen to break down the lactic acid and meet the oxygen shortage created during the race.", solution: "Extra oxygen is needed to deal with the lactic acid and restore aerobic respiration." },
      { label: "(c)", marks: 2, body: "Compare the respiration in Arjun's muscles during the race with the respiration of yeast in the dough.", answer: "Both are anaerobic and start with glucose broken down to pyruvate in the cytoplasm. In muscles, pyruvate becomes lactic acid and energy; in yeast, pyruvate becomes ethanol, carbon dioxide and energy. The CO₂ made by yeast makes the dough rise.", solution: "1 mark: both anaerobic via pyruvate. 1 mark: lactic acid vs ethanol + CO₂ (dough rises)." },
    ],
  },
  {
    key: "alveoli-high-altitude", topic: "lp-respiration", difficulty: H,
    passage: "Mountaineers climbing very high peaks often breathe faster and feel tired easily because the air there contains less oxygen. Over a few weeks at high altitude, the body makes more red blood cells. In the lungs, air reaches millions of tiny balloon-like sacs whose thin walls are surrounded by blood capillaries.",
    parts: [
      { label: "(a)", marks: 1, body: "Name the tiny balloon-like sacs in the lungs.", answer: "Alveoli.", solution: "Alveoli are the site of gas exchange." },
      { label: "(b)", marks: 1, body: "Which pigment in red blood cells carries oxygen?", answer: "Haemoglobin.", solution: "Haemoglobin has a high affinity for oxygen." },
      { label: "(c)", marks: 2, body: "Explain why making more red blood cells helps a mountaineer at high altitude.", answer: "More red blood cells means more haemoglobin, so more oxygen can be picked up from the thin air in the alveoli and carried to the tissues, reducing tiredness.", solution: "1 mark: more haemoglobin. 1 mark: more oxygen carried to tissues despite low oxygen in air." },
    ],
  },
  {
    key: "heart-chambers", topic: "lp-transport-human", difficulty: M,
    passage: "A biology teacher showed a model of the human heart. She pointed out that it has four chambers and that the walls of two of the chambers are much thicker than the others. She explained that the right side of the heart handles one kind of blood and the left side another, and that flaps between the chambers stop the blood from flowing the wrong way.",
    parts: [
      { label: "(a)", marks: 1, body: "Which two chambers have thicker walls?", answer: "The ventricles (right and left ventricles).", solution: "Ventricles pump blood out of the heart to the lungs and body." },
      { label: "(b)", marks: 1, body: "What kind of blood does the right side of the heart handle?", answer: "Deoxygenated blood.", solution: "The right side receives deoxygenated blood from the body and pumps it to the lungs." },
      { label: "(c)", marks: 2, body: "What are the flaps called, and what would happen if they did not work properly?", answer: "Valves. If they did not work, blood would flow backwards when the chambers contract, so the heart would pump less efficiently and the body would get less oxygenated blood.", solution: "1 mark: valves. 1 mark: backflow → inefficient pumping / less oxygen to the body." },
    ],
  },
  {
    key: "blood-pressure", topic: "lp-transport-human", difficulty: H,
    passage: "During a health camp, a nurse measured the blood pressure of several people. One man's reading was 150/100 mm Hg. The nurse said this was high, and that it could be caused by narrowing of the small arteries (arterioles), which increases resistance to blood flow. She advised him to see a doctor, because high blood pressure can cause a blood vessel to burst.",
    parts: [
      { label: "(a)", marks: 1, body: "Name the instrument used to measure blood pressure.", answer: "Sphygmomanometer.", solution: "A sphygmomanometer measures blood pressure." },
      { label: "(b)", marks: 1, body: "What is the normal blood pressure of a healthy adult?", answer: "About 120/80 mm Hg.", solution: "Systolic about 120 mm Hg, diastolic about 80 mm Hg." },
      { label: "(c)", marks: 2, body: "In the reading 150/100 mm Hg, what do 150 and 100 stand for? Why is this reading a concern?", answer: "150 is the systolic pressure (during ventricular contraction) and 100 is the diastolic pressure (during ventricular relaxation). Both are above normal, showing hypertension, which strains the heart and can rupture blood vessels, causing internal bleeding.", solution: "1 mark: systolic and diastolic correctly identified. 1 mark: hypertension and its risk." },
    ],
  },
  {
    key: "tree-water", topic: "lp-transport-plant", difficulty: M,
    passage: "A student placed a leafy white-flowered balsam shoot in water coloured with red ink and kept it in sunlight. After a few hours, red streaks were seen in the stem and the veins of the leaves turned red. A similar shoot with all its leaves removed took much longer to show any colour.",
    parts: [
      { label: "(a)", marks: 1, body: "Through which tissue did the coloured water move up the stem?", answer: "Xylem.", solution: "Xylem conducts water and minerals upwards." },
      { label: "(b)", marks: 1, body: "Name the process by which water was lost from the leaves.", answer: "Transpiration.", solution: "Water evaporates mainly through the stomata of the leaves." },
      { label: "(c)", marks: 2, body: "Why did the shoot without leaves take much longer to show colour?", answer: "Without leaves there is almost no transpiration, so there is no transpiration pull; water is not pulled up the xylem quickly, and the coloured water rises very slowly.", solution: "1 mark: no leaves → little transpiration. 1 mark: no suction/transpiration pull to draw water up." },
    ],
  },
  {
    key: "kidney-dialysis", topic: "lp-excretion-human", difficulty: H,
    passage: "Mr Sharma's kidneys stopped working properly after a long illness. His doctor put him on haemodialysis three times a week. During each session his blood is passed through long tubes with a semi-permeable lining that sit in a tank of dialysing fluid. The fluid has the same osmotic pressure as blood but contains no nitrogenous waste. Purified blood is returned to his body.",
    parts: [
      { label: "(a)", marks: 1, body: "Name the main nitrogenous waste removed from Mr Sharma's blood during dialysis.", answer: "Urea.", solution: "Urea is the main nitrogenous waste in humans." },
      { label: "(b)", marks: 1, body: "By what process do the wastes pass from the blood into the dialysing fluid?", answer: "Diffusion.", solution: "Wastes move from high concentration in blood to low concentration in the fluid." },
      { label: "(c)", marks: 2, body: "Give one way in which the artificial kidney works differently from Mr Sharma's natural kidneys, and one reason why a natural kidney is better.", answer: "The artificial kidney has no reabsorption; it only removes wastes by diffusion. A natural kidney filters blood continuously and selectively reabsorbs glucose, amino acids, salts and water as the body needs, so it keeps the body's balance better.", solution: "1 mark: no reabsorption in dialysis. 1 mark: natural kidney works continuously with selective reabsorption." },
    ],
  },
];
